/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmr.garments;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.DriverManager;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.Border;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author HP
 */
public class BalanceFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public BalanceFrame(String contact) {
        initComponents(); 
        menu.setVisible(false);
        setExtendedState(this.MAXIMIZED_BOTH); 
        createConnection();
        pfcontact=contact;
        showDate();
    }
    public void createConnection()
    {
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/GarmentsShop","root","root");
            }
        catch(Exception e)
        {
            
        }
    } 
    public void showDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        cdate=s.format(d);
        pdate="Date : "+s.format(d);
    }    
    public void showTime()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("hh:mm aa");
        ptime="Time : "+s.format(d);
    }    
    public void getClearIconBorder()
    {
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        retaillogo.setBorder(b);
        wholesalelogo.setBorder(b);
        customerlogo.setBorder(b);
        stocklogo.setBorder(b);
        employeelogo.setBorder(b);
        balancelogo.setBorder(b);
    }
    public void getClearPanelBorder()
    {
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p1.setBorder(b);
        p2.setBorder(b);
        p3.setBorder(b);
        p4.setBorder(b);
        p5.setBorder(b);
        p6.setBorder(b);
    }
    public void openMenu()
    {
        Thread th=new Thread(){
            @Override
            public void run(){
                Toggle.setVisible(false);
                menu.setVisible(true);
                try{
                    for(int i=0;i<305;i++)
                    {
                        Thread.sleep(1);
                        menu.setSize(i,768);
                    }
                }
                catch(Exception e)
                {
                    System.out.println("Error");
                }
            }
        };th.start();
    }
    
    public void closeMenu()
    {
        Thread th=new Thread(){
            @Override
            public void run(){
                try{
                    for(int i=305;i>=0;i--)
                    {
                        Thread.sleep(1);
                        menu.setSize(i,768);
                    }
                Toggle.setVisible(true);
                menu.setVisible(false);
                }
                catch(Exception e)
                {
                    System.out.println("Error");
                }
            }
        };th.start();
        p1.setBackground(new Color(187,120,52,255));
        p2.setBackground(new Color(187,120,52,255));
        p3.setBackground(new Color(187,120,52,255));
        p4.setBackground(new Color(187,120,52,255));
        p5.setBackground(new Color(187,120,52,255));
        p6.setBackground(new Color(187,120,52,255));  
    }
    public void getClear()
    {
        p1.setBackground(new Color(187,120,52,255));
        p2.setBackground(new Color(187,120,52,255));
        p3.setBackground(new Color(187,120,52,255));
        p4.setBackground(new Color(187,120,52,255));
        p5.setBackground(new Color(187,120,52,255));
        p6.setBackground(new Color(187,120,52,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IconBar = new javax.swing.JPanel();
        Toggle = new javax.swing.JLabel();
        retaillogo = new javax.swing.JLabel();
        wholesalelogo = new javax.swing.JLabel();
        customerlogo = new javax.swing.JLabel();
        employeelogo = new javax.swing.JLabel();
        balancelogo = new javax.swing.JLabel();
        stocklogo = new javax.swing.JLabel();
        profilelogo = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        l6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        l7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        retailpanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jc4 = new com.toedter.calendar.JDateChooser();
        jc5 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        retailpanel4 = new javax.swing.JPanel();
        p9 = new javax.swing.JPanel();
        jc1 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jc3 = new com.toedter.calendar.JDateChooser();
        jLabel42 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jc7 = new com.toedter.calendar.JDateChooser();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconBar.setBackground(new java.awt.Color(187, 120, 52));
        IconBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Toggle.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Toggle.png")); // NOI18N
        Toggle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Toggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToggleMouseClicked(evt);
            }
        });
        IconBar.add(Toggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 30, 40, 40));

        retaillogo.setBackground(new java.awt.Color(102, 102, 102));
        retaillogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        retaillogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Retail.png")); // NOI18N
        retaillogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        retaillogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retaillogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                retaillogoMouseEntered(evt);
            }
        });
        IconBar.add(retaillogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 47));

        wholesalelogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wholesalelogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Wholesale.png")); // NOI18N
        wholesalelogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wholesalelogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wholesalelogoMouseClicked(evt);
            }
        });
        IconBar.add(wholesalelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, 47));

        customerlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerlogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Customer Management.png")); // NOI18N
        customerlogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        customerlogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerlogoMouseClicked(evt);
            }
        });
        IconBar.add(customerlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 50, 47));

        employeelogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeelogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Employee Management.png")); // NOI18N
        employeelogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeelogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeelogoMouseClicked(evt);
            }
        });
        IconBar.add(employeelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 50, 50));

        balancelogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balancelogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Balance Analysis.png")); // NOI18N
        balancelogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balancelogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balancelogoMouseClicked(evt);
            }
        });
        IconBar.add(balancelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 50, 47));

        stocklogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stocklogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Stock Management.png")); // NOI18N
        stocklogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stocklogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stocklogoMouseClicked(evt);
            }
        });
        IconBar.add(stocklogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 50, 47));

        profilelogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilelogo.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\profile.png")); // NOI18N
        profilelogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profilelogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilelogoMouseClicked(evt);
            }
        });
        IconBar.add(profilelogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 50, 47));

        getContentPane().add(IconBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 768));

        menu.setBackground(new java.awt.Color(187, 120, 52));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(187, 120, 52));
        p1.setForeground(new java.awt.Color(204, 204, 204));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setBackground(new java.awt.Color(67, 48, 44));
        l1.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l1.setText("Retail");
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l1MouseExited(evt);
            }
        });
        p1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 47));

        p2.setBackground(new java.awt.Color(187, 120, 52));
        p2.setForeground(new java.awt.Color(204, 204, 204));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setBackground(new java.awt.Color(204, 204, 204));
        l2.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l2.setText("Wholesale");
        l2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l2MouseExited(evt);
            }
        });
        p2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 47));

        p3.setBackground(new java.awt.Color(187, 120, 52));
        p3.setForeground(new java.awt.Color(204, 204, 204));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l3.setBackground(new java.awt.Color(204, 204, 204));
        l3.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l3.setText("Customer Management");
        l3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l3MouseExited(evt);
            }
        });
        p3.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, 47));

        p4.setBackground(new java.awt.Color(187, 120, 52));
        p4.setForeground(new java.awt.Color(204, 204, 204));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l4.setBackground(new java.awt.Color(204, 204, 204));
        l4.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l4.setText("Employee Management");
        l4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l4MouseExited(evt);
            }
        });
        p4.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 280, 47));

        p5.setBackground(new java.awt.Color(187, 120, 52));
        p5.setForeground(new java.awt.Color(204, 204, 204));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l5.setBackground(new java.awt.Color(204, 204, 204));
        l5.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l5.setText("Stock Management");
        l5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l5MouseExited(evt);
            }
        });
        p5.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 47));

        menu.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 280, 47));

        p6.setBackground(new java.awt.Color(187, 120, 52));
        p6.setForeground(new java.awt.Color(204, 204, 204));
        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l6.setBackground(new java.awt.Color(204, 204, 204));
        l6.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l6.setText("Balance Analysis");
        l6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l6MouseExited(evt);
            }
        });
        p6.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 280, 47));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Cross.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 30, 40));

        p7.setBackground(new java.awt.Color(187, 120, 52));
        p7.setForeground(new java.awt.Color(204, 204, 204));
        p7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l7.setBackground(new java.awt.Color(204, 204, 204));
        l7.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        l7.setText("User Profile");
        l7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l7MouseExited(evt);
            }
        });
        p7.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 47));

        menu.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 280, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Webp.net-resizeimage.png")); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 710, 130, 50));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 305, 768));

        retailpanel5.setBackground(new java.awt.Color(0, 0, 0,70));
        retailpanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(225, 162, 81), new java.awt.Color(225, 162, 81)));
        retailpanel5.setPreferredSize(new java.awt.Dimension(700, 307));
        retailpanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Profit Statement");
        retailpanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, -1));

        jLabel32.setBackground(new java.awt.Color(204, 204, 204));
        jLabel32.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 204));
        jLabel32.setText("To");
        retailpanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 50, 35));

        jc4.setBackground(new java.awt.Color(249, 215, 184));
        jc4.setDateFormatString("YYYY-MM-dd");
        retailpanel5.add(jc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, 35));

        jc5.setBackground(new java.awt.Color(249, 215, 184));
        jc5.setDateFormatString("YYYY-MM-dd");
        retailpanel5.add(jc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 180, 35));

        receipt.setColumns(20);
        receipt.setLineWrap(true);
        receipt.setRows(5);
        receipt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));
        jScrollPane1.setViewportView(receipt);

        retailpanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 270, 480));

        jLabel34.setBackground(new java.awt.Color(204, 204, 204));
        jLabel34.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setText("From");
        retailpanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 60, 35));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Search-Icon.png")); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        retailpanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        getContentPane().add(retailpanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 410, 710));

        retailpanel4.setBackground(new java.awt.Color(0, 0, 0,70));
        retailpanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(225, 162, 81), new java.awt.Color(225, 162, 81)));
        retailpanel4.setPreferredSize(new java.awt.Dimension(700, 307));
        retailpanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p9.setBackground(new java.awt.Color(204, 255, 255));
        p9.setLayout(new java.awt.BorderLayout());
        retailpanel4.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 770, 390));

        jc1.setBackground(new java.awt.Color(249, 215, 184));
        jc1.setDateFormatString("YYYY-MM-dd");
        retailpanel4.add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 255, 150, 35));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Balance Analysis");
        retailpanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 770, -1));

        jLabel41.setBackground(new java.awt.Color(204, 204, 204));
        jLabel41.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 204));
        jLabel41.setText("Total Income");
        retailpanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 220, 30));

        tf1.setEditable(false);
        tf1.setBackground(new java.awt.Color(249, 215, 184));
        tf1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf1FocusGained(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        retailpanel4.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 180, 30));

        jLabel29.setBackground(new java.awt.Color(204, 204, 204));
        jLabel29.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 204));
        jLabel29.setText("From");
        retailpanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 35));

        jLabel30.setBackground(new java.awt.Color(204, 204, 204));
        jLabel30.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 204));
        jLabel30.setText("To");
        retailpanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 30, 35));

        jc3.setBackground(new java.awt.Color(249, 215, 184));
        jc3.setDateFormatString("YYYY-MM-dd");
        jc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc3MouseClicked(evt);
            }
        });
        retailpanel4.add(jc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 35));

        jLabel42.setBackground(new java.awt.Color(204, 204, 204));
        jLabel42.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 204));
        jLabel42.setText("Worker Investment");
        retailpanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 165, 220, 30));

        tf2.setEditable(false);
        tf2.setBackground(new java.awt.Color(249, 215, 184));
        tf2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        tf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
        });
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        retailpanel4.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 165, 180, 30));

        tf3.setEditable(false);
        tf3.setBackground(new java.awt.Color(249, 215, 184));
        tf3.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        tf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf3FocusGained(evt);
            }
        });
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        retailpanel4.add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 180, 30));

        jLabel44.setBackground(new java.awt.Color(204, 204, 204));
        jLabel44.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 204));
        jLabel44.setText("Profit");
        retailpanel4.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Search-Icon.png")); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        retailpanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 255, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Search-Icon.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        retailpanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jLabel31.setBackground(new java.awt.Color(204, 204, 204));
        jLabel31.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 204));
        jLabel31.setText("Graph of Last 10 Days(Amount vs Date) From");
        retailpanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 255, 480, 35));

        jc7.setBackground(new java.awt.Color(249, 215, 184));
        jc7.setDateFormatString("YYYY-MM-dd");
        jc7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jc7FocusLost(evt);
            }
        });
        retailpanel4.add(jc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 130, 35));

        getContentPane().add(retailpanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 810, 710));

        bgimage.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\ForgetPasswordBackground.png")); // NOI18N
        getContentPane().add(bgimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Connection con;
String cdate,ptime,pdate,pfcontact="";
    private void ToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToggleMouseClicked
        openMenu();
    }//GEN-LAST:event_ToggleMouseClicked

    private void l1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseEntered
        getClear();
        p1.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p1.setBorder(b);
    }//GEN-LAST:event_l1MouseEntered

    private void l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseEntered
        getClear();
        p2.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p2.setBorder(b);
    }//GEN-LAST:event_l2MouseEntered

    private void l3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseEntered
        getClear();
        p3.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p3.setBorder(b);
    }//GEN-LAST:event_l3MouseEntered

    private void l4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseEntered
        getClear();
        p4.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p4.setBorder(b);
    }//GEN-LAST:event_l4MouseEntered

    private void l5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseEntered
        getClear();
        p5.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p5.setBorder(b);
    }//GEN-LAST:event_l5MouseEntered

    private void l6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseEntered
        getClear();
        p6.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p6.setBorder(b);
    }//GEN-LAST:event_l6MouseEntered

    private void l1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseExited
        p1.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p1.setBorder(b);
    }//GEN-LAST:event_l1MouseExited

    private void l2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseExited
        p2.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p2.setBorder(b);
    }//GEN-LAST:event_l2MouseExited

    private void l3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseExited
        p3.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p3.setBorder(b);
    }//GEN-LAST:event_l3MouseExited

    private void l4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseExited
        p4.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p4.setBorder(b);
    }//GEN-LAST:event_l4MouseExited

    private void l5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseExited
        p5.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p5.setBorder(b);
    }//GEN-LAST:event_l5MouseExited

    private void l6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseExited
        p6.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p6.setBorder(b);
    }//GEN-LAST:event_l6MouseExited

    private void retaillogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retaillogoMouseClicked

        RetailFrame r=new RetailFrame(pfcontact);
        r.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_retaillogoMouseClicked

    private void wholesalelogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wholesalelogoMouseClicked
        WholeSaleFrame w=new WholeSaleFrame(pfcontact);
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wholesalelogoMouseClicked

    private void customerlogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerlogoMouseClicked
        CustomerFrame c=new CustomerFrame(pfcontact);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerlogoMouseClicked

    private void employeelogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeelogoMouseClicked
        getClear();
        p4.setBackground(new Color(225,162,81,255));
        EmployeeFrame e=new EmployeeFrame(pfcontact);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_employeelogoMouseClicked

    private void stocklogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stocklogoMouseClicked
        StockFrame s=new StockFrame(pfcontact);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stocklogoMouseClicked

    private void balancelogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balancelogoMouseClicked
        BalanceFrame b=new BalanceFrame(pfcontact);
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_balancelogoMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        closeMenu();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void retaillogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retaillogoMouseEntered
       
    }//GEN-LAST:event_retaillogoMouseEntered

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        RetailFrame r=new RetailFrame(pfcontact);
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l1MouseClicked
    String datearray[]=new String[10];
    int totalamount[]=new int[10];
    int windowcount=0;
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        balancelogo.setBorder(b);
        profilelogo.setBorder(null);
        if(windowcount==0)
        {
            Date d = null;
            int count=0;
            try {
                d = new SimpleDateFormat("yyyy-MM-dd").parse(cdate);
            } catch (ParseException ex) {
                Logger.getLogger(BalanceFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            jc1.setDate(d);
            SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
            String userdate=((JTextField)jc1.getDateEditor().getUiComponent()).getText();
            Calendar c=Calendar.getInstance();
            try{
            c.setTime(s.parse(userdate));
            }catch(Exception e){

            }
            c.add(Calendar.DAY_OF_MONTH,-9);
            String oldDate=s.format(c.getTime());
            System.out.println(oldDate);
            System.out.println(cdate);

            try
            {
                Statement st=con.createStatement();
                ResultSet rs2 =st.executeQuery("Select count(distinct(Date)) from customerinfo where Date between '"+oldDate+"' and '"+cdate+"' order by Date");
                while(rs2.next())
                {
                    datearray=new String[rs2.getInt("count(distinct(Date))")];
                    totalamount=new int[rs2.getInt("count(distinct(Date))")];
                }
                count=0;
                ResultSet rs3 =st.executeQuery("Select distinct(Date) from customerinfo where Date between '"+oldDate+"' and '"+cdate+"' order by Date");
                while(rs3.next())
                {
                    datearray[count++]=rs3.getString("Date");
                }
            }
            catch(Exception e)
            {
                System.out.println("something went wrong");
            }
            try
            {
                Statement st=con.createStatement();
                for(int i=0;i<datearray.length;i++)
                {
                    ResultSet rs=st.executeQuery("Select sum(TotalAmount) from customerinfo where Date='"+datearray[i]+"'");
                    while(rs.next())
                    {
                        totalamount[i]=rs.getInt("sum(TotalAmount)");
                    }
                }
            }
            catch(Exception e)
            {

            }
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
            for(int i=0;i<datearray.length;i++)
            {
                dataset.setValue(totalamount[i],"Amount",datearray[i].substring(8, 10));
            }
            JFreeChart barchart=ChartFactory.createLineChart("Balance Analysis", "Date", "Amount",dataset, PlotOrientation.VERTICAL, false,true,true);
            CategoryPlot plot=barchart.getCategoryPlot();

            plot.setRangeGridlinePaint(Color.black);
            plot.setBackgroundPaint(new Color(249,215,184,255));
            ChartPanel barPanel=new ChartPanel(barchart);
            p9.removeAll();
            p9.add(barPanel,BorderLayout.CENTER);
            p9.validate();
            System.out.println("Success");
            windowcount++;
        }
        else
        {
            
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        WholeSaleFrame w=new WholeSaleFrame(pfcontact);
        w.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        CustomerFrame c=new CustomerFrame(pfcontact);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
        EmployeeFrame e=new EmployeeFrame(pfcontact);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
        StockFrame s=new StockFrame(pfcontact);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
        BalanceFrame b=new BalanceFrame(pfcontact);
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_l6MouseClicked

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited

    }//GEN-LAST:event_menuMouseExited

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked

    }//GEN-LAST:event_menuMouseClicked

    private void tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1FocusGained

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2FocusGained

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf3FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3FocusGained

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Date d = null;
        int count=0;
        String userdate=((JTextField)jc1.getDateEditor().getUiComponent()).getText();
        try {
            d = new SimpleDateFormat("yyyy-MM-dd").parse(userdate);
        } catch (ParseException ex) {
            Logger.getLogger(BalanceFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        jc1.setDate(d);
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        Calendar c=Calendar.getInstance();
        try{
            c.setTime(s.parse(userdate));
        }catch(Exception e){
            
        }
            
        c.add(Calendar.DAY_OF_MONTH,-9);
        
        String oldDate=s.format(c.getTime());
        System.out.println(oldDate);
        System.out.println(userdate);
        
        try
        {
            Statement st=con.createStatement();
            ResultSet rs2 =st.executeQuery("Select count(distinct(Date)) from customerinfo where Date between '"+oldDate+"' and '"+userdate+"' order by Date");
            while(rs2.next())
            {
                datearray=new String[rs2.getInt("count(distinct(Date))")];
                totalamount=new int[rs2.getInt("count(distinct(Date))")];
            }
            count=0;
            ResultSet rs3 =st.executeQuery("Select distinct(Date) from customerinfo where Date between '"+oldDate+"' and '"+userdate+"' order by Date");
            while(rs3.next())
            {
                datearray[count++]=rs3.getString("Date");
            }
        }
        catch(Exception e)
        {
            System.out.println("something went wrong");
        }
        try
        {
            Statement st=con.createStatement();
            for(int i=0;i<datearray.length;i++)
            {
                ResultSet rs=st.executeQuery("Select sum(TotalAmount) from customerinfo where Date='"+datearray[i]+"'");
                while(rs.next())
                {
                    totalamount[i]=rs.getInt("sum(TotalAmount)");
                }
            }
        }
        catch(Exception e)
        {
            
        }
        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        for(int i=0;i<datearray.length;i++)
        {
            dataset.setValue(totalamount[i],"Amount",datearray[i].substring(8, 10));
        }
        JFreeChart barchart=ChartFactory.createLineChart("Balance Analysis", "Date", "Amount",dataset, PlotOrientation.VERTICAL, false,true,true);
        CategoryPlot plot=barchart.getCategoryPlot();
        
        plot.setRangeGridlinePaint(Color.black);
        plot.setBackgroundPaint(new Color(249,215,184,255));
        ChartPanel barPanel=new ChartPanel(barchart);
        p9.removeAll();
        p9.add(barPanel,BorderLayout.CENTER);
        p9.validate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    String from=((JTextField)jc7.getDateEditor().getUiComponent()).getText();
    String to=((JTextField)jc3.getDateEditor().getUiComponent()).getText();
    try
    {
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("Select sum(TotalAmount) from customerinfo where Date between '"+from+"' and '"+to+"'");
        while(rs.next())
        {
            tf1.setText(""+rs.getInt("sum(TotalAmount)"));
        }
        ResultSet rs1=st.executeQuery("select sum(SalaryGiven) from employeesalarygiven where Date between '"+from+"' and '"+to+"'");
        while(rs1.next())
        {
            tf2.setText(""+rs1.getInt("sum(SalaryGiven)"));
        }
        ResultSet rs2=st.executeQuery("select sum(ProfitEarned) from customerinfo where Date between '"+from+"' and '"+to+"'");
        while(rs2.next())
        {
            tf3.setText(""+rs2.getInt("sum(ProfitEarned)"));
        }
    }
    catch(Exception e)
    {
        System.out.println("Error");;
    }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jc7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jc7FocusLost

    }//GEN-LAST:event_jc7FocusLost

    private void jc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc3MouseClicked

    }//GEN-LAST:event_jc3MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        int count=0;
        String datearray[]=null;
        showDate();
        showTime();
        String from=((JTextField)jc5.getDateEditor().getUiComponent()).getText();
        String to=((JTextField)jc4.getDateEditor().getUiComponent()).getText();        
        receipt.append("\n\tRMR GARMENTS\n");
        receipt.append("                            18/5 Sindhi Colony\n");
        receipt.append("                                  9826782684\n");        
        receipt.append("     "+pdate+"            "+ptime+"\n\n");
        receipt.append("                               Profit Statement\n");        
        receipt.append("    From : "+from+"             To : "+to+"\n");
        receipt.append("     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
        receipt.append("          Date                 Sales                   Profit\n");
        try
        {
            Statement st=con.createStatement();
            ResultSet rs1=st.executeQuery("Select count(distinct(Date)) from customerinfo where Date between '"+from+"' and '"+to+"'");
            while(rs1.next())
            {
                datearray=new String[rs1.getInt("count(distinct(Date))")];
            }
            ResultSet rs2=st.executeQuery("select distinct(Date) from customerinfo where Date between '"+from+"' and '"+to+"'");
            while(rs2.next())
            {
                datearray[count++]=rs2.getString("Date");
            }
            for(int i=0;i<datearray.length;i++)
            {
                ResultSet rs3=st.executeQuery("select sum(TotalAmount),sum(ProfitEarned) from customerinfo where Date='"+datearray[i]+"'");
                while(rs3.next())
                {
                    System.out.println(rs3.getInt("sum(TotalAmount)"));
                    receipt.append("     "+datearray[i]+"            "+rs3.getInt("sum(TotalAmount)")+"                      "+rs3.getInt("sum(ProfitEarned)")+"\n");
                }
            }
            receipt.append("     - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n");
            ResultSet rs=st.executeQuery("select sum(TotalAmount),sum(ProfitEarned) from customerinfo where Date between '"+from+"' and '"+to+"'");
            while(rs.next())
            {
                receipt.append("     Total Revenue                                    "+rs.getInt("sum(TotalAmount)")+"\n");
                receipt.append("     Total Profit                                            "+rs.getInt("sum(ProfitEarned)")+"\n");
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void profilelogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilelogoMouseClicked
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        profilelogo.setBorder(b);
        balancelogo.setBorder(null);
        ProfilePage b1=new ProfilePage(pfcontact);
        b1.setVisible(true);
    }//GEN-LAST:event_profilelogoMouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        profilelogo.setBorder(b);
        balancelogo.setBorder(null);
        ProfilePage b1=new ProfilePage(pfcontact);
        b1.setVisible(true);
    }//GEN-LAST:event_l7MouseClicked

    private void l7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseEntered
        getClear();
        p7.setBackground(new Color(225,162,81,255));
        getClearPanelBorder();
        Border b=BorderFactory.createBevelBorder(1, new Color(204,204,255,255), new Color(225,162,81,255));
        p7.setBorder(b);
    }//GEN-LAST:event_l7MouseEntered

    private void l7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseExited
        p7.setBackground(new Color(187,120,52,255));
        Border b=BorderFactory.createLineBorder(new Color(187,120,52,255), 1);
        p7.setBorder(b);
    }//GEN-LAST:event_l7MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        LogoutPage lp=new LogoutPage();
        lp.setVisible(true);
        LogoutSuccess l=new LogoutSuccess();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a="";
                new BalanceFrame(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IconBar;
    private javax.swing.JLabel Toggle;
    private javax.swing.JLabel balancelogo;
    private javax.swing.JLabel bgimage;
    private javax.swing.JLabel customerlogo;
    private javax.swing.JLabel employeelogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jc1;
    private com.toedter.calendar.JDateChooser jc3;
    private com.toedter.calendar.JDateChooser jc4;
    private com.toedter.calendar.JDateChooser jc5;
    private com.toedter.calendar.JDateChooser jc7;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p9;
    private javax.swing.JLabel profilelogo;
    private javax.swing.JTextArea receipt;
    private javax.swing.JLabel retaillogo;
    private javax.swing.JPanel retailpanel4;
    private javax.swing.JPanel retailpanel5;
    private javax.swing.JLabel stocklogo;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JLabel wholesalelogo;
    // End of variables declaration//GEN-END:variables
}
