/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmr.garments;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class EmployeeExtraDetails extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeExtraDetails
     */
    public EmployeeExtraDetails(String contact) {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH); 
        createConnection();
        pfcontact=contact;
    }
    public void createConnection()
    {
        try
            {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/GarmentsShop","root","root");
            con.setAutoCommit(false);
            }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginform = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jc1 = new com.toedter.calendar.JDateChooser();
        jc2 = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginform.setBackground(new java.awt.Color(0, 0, 0,120));
        loginform.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 102, 0), new java.awt.Color(153, 153, 153)));
        loginform.setPreferredSize(new java.awt.Dimension(700, 307));
        loginform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Back Image.png")); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        loginform.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 100, 36));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Absent Details");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198)));
        loginform.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 210, -1));

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Total Expenses");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198)));
        loginform.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 525, 170, 30));

        jLabel21.setBackground(new java.awt.Color(204, 204, 204));
        jLabel21.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("From");
        loginform.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 115, 60, 35));

        jc1.setBackground(new java.awt.Color(249, 215, 184));
        jc1.setDateFormatString("YYYY-MM-dd");
        jc1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        loginform.add(jc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 115, 150, 35));

        jc2.setBackground(new java.awt.Color(249, 215, 184));
        jc2.setDateFormatString("YYYY-MM-dd");
        jc2.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        loginform.add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 115, 150, 35));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setText("to");
        loginform.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 115, 30, 35));

        jScrollPane1.setFont(new java.awt.Font("Cambria Math", 0, 22)); // NOI18N

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "Salary", "Date", "From", "To", "Salary Given", "Expenses", "Holidays"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);
        if (tb1.getColumnModel().getColumnCount() > 0) {
            tb1.getColumnModel().getColumn(0).setResizable(false);
            tb1.getColumnModel().getColumn(0).setPreferredWidth(30);
            tb1.getColumnModel().getColumn(1).setResizable(false);
            tb1.getColumnModel().getColumn(2).setResizable(false);
            tb1.getColumnModel().getColumn(3).setResizable(false);
            tb1.getColumnModel().getColumn(4).setResizable(false);
            tb1.getColumnModel().getColumn(5).setResizable(false);
            tb1.getColumnModel().getColumn(6).setResizable(false);
            tb1.getColumnModel().getColumn(7).setResizable(false);
        }

        loginform.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 167, 783, 173));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Search-Icon.png")); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        loginform.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 115, 35, 35));

        cb1.setBackground(new java.awt.Color(249, 215, 184));
        cb1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select EMP ID" }));
        cb1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(187, 120, 52), new java.awt.Color(0, 0, 0)));
        cb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        loginform.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 115, 145, 35));

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb3);
        if (tb3.getColumnModel().getColumnCount() > 0) {
            tb3.getColumnModel().getColumn(0).setResizable(false);
            tb3.getColumnModel().getColumn(0).setPreferredWidth(100);
            tb3.getColumnModel().getColumn(1).setResizable(false);
            tb3.getColumnModel().getColumn(1).setPreferredWidth(240);
        }

        loginform.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 340, 110));

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Emp ID");
        loginform.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 115, 80, 35));

        tf1.setEditable(false);
        tf1.setBackground(new java.awt.Color(249, 215, 184));
        tf1.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        tf1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf1FocusGained(evt);
            }
        });
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        loginform.add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 525, 150, 30));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SNO", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tb2);
        if (tb2.getColumnModel().getColumnCount() > 0) {
            tb2.getColumnModel().getColumn(0).setResizable(false);
            tb2.getColumnModel().getColumn(0).setPreferredWidth(100);
            tb2.getColumnModel().getColumn(1).setResizable(false);
            tb2.getColumnModel().getColumn(1).setPreferredWidth(110);
            tb2.getColumnModel().getColumn(2).setResizable(false);
            tb2.getColumnModel().getColumn(2).setPreferredWidth(130);
        }

        loginform.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 340, 110));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Total Holidays");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198)));
        loginform.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 525, 160, 30));

        tf2.setEditable(false);
        tf2.setBackground(new java.awt.Color(249, 215, 184));
        tf2.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        tf2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
        });
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        loginform.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 525, 160, 30));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Cambria Math", 1, 25)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("                               Employee Extra Details");
        loginform.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 790, -1));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Salary Details");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198)));
        loginform.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 220, -1));

        jLabel15.setBackground(new java.awt.Color(204, 204, 204));
        jLabel15.setFont(new java.awt.Font("Cambria Math", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Expenses Details");
        jLabel15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198), new java.awt.Color(204, 223, 198)));
        loginform.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 230, -1));

        getContentPane().add(loginform, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 94, 900, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\ForgetPasswordBackground.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1370, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Connection con;
String pfcontact="";
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        EmployeeDetailsTableFormat e=new EmployeeDetailsTableFormat(pfcontact);
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
String from,to;
int eid=0,sno=0,windowcount=0;
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int sum=0;
        String tempeid=cb1.getSelectedItem().toString();
        from=((JTextField)jc1.getDateEditor().getUiComponent()).getText();
        to=((JTextField)jc2.getDateEditor().getUiComponent()).getText();
        if(tempeid.equals("Select EMP ID"))
        {
            SelectEMPID s=new SelectEMPID();
            s.setVisible(true);
        }
        else
        {
        eid=Integer.parseInt(tempeid);
        DefaultTableModel model=(DefaultTableModel)tb1.getModel();
        try
        {
            while(model.getRowCount()>0)
            {
                for(int i=0;i<model.getRowCount();i++)
                model.removeRow(i);
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/garmentsshop","root","root");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from employeesalarygiven where Date between '"+from+"' and '"+to+"' and EID="+eid+"");
            while(rs.next())
            {
                sno++;
                model.addRow(new Object[]{sno,rs.getInt(2),rs.getString(8),rs.getString(3),rs.getString(4),rs.getInt(5),rs.getInt(6),rs.getInt(7)});
            }
            con.close();
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
        sno=0;
        DefaultTableModel model1=(DefaultTableModel)tb2.getModel();
        try
        {
            while(model1.getRowCount()>0)
            {
                for(int i=0;i<model1.getRowCount();i++)
                model1.removeRow(i);
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/garmentsshop","root","root");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from employeeexpenses where Date between '"+from+"' and '"+to+"' and EID="+eid+"");
            while(rs.next())
            {
                sno++;
                model1.addRow(new Object[]{sno,rs.getInt(2),rs.getString(3)});
            }
            ResultSet rs1=st.executeQuery("select sum(Amount) from employeeexpenses where Date between '"+from+"' and '"+to+"' and EID="+eid+"");
            while(rs1.next())
            {
                sum=rs1.getInt("sum(Amount)");
            }
            tf1.setText(""+sum);
            con.close();
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
        sno=0;
        DefaultTableModel model2=(DefaultTableModel)tb3.getModel();
        try
        {
            while(model2.getRowCount()>0)
            {
                for(int i=0;i<model2.getRowCount();i++)
                model2.removeRow(i);
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/garmentsshop","root","root");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from employeeabsentdetails where Date between '"+from+"' and '"+to+"' and EID="+eid+"");
            while(rs.next())
            {
                sno++;
                model2.addRow(new Object[]{sno,rs.getString(2)});
            }
            ResultSet rs1=st.executeQuery("select count(EID) from employeeabsentdetails where Date between '"+from+"' and '"+to+"' and EID="+eid+"");
            while(rs1.next())
            {
                sum=rs1.getInt("count(EID)");
            }
            tf2.setText(""+sum);
            con.close();
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged

    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed

    }//GEN-LAST:event_cb1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       if(windowcount==0)
       {
        try
        {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select distinct(EID) from employeedetails");
            while(rs.next())
            {
                cb1.addItem(""+rs.getInt("EID"));
            }
        }
        catch(Exception e)
        {
            System.out.println("Error");
        }
        windowcount++;
       }
       else
       {
           
       }
    }//GEN-LAST:event_formWindowGainedFocus

    private void tf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf1FocusGained

    }//GEN-LAST:event_tf1FocusGained

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2FocusGained

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeExtraDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeExtraDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeExtraDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeExtraDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a="";
                new EmployeeExtraDetails(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jc1;
    private com.toedter.calendar.JDateChooser jc2;
    private javax.swing.JPanel loginform;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
