/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmr.garments;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.awt.print.*;
import java.text.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.JTextField;
public class EmployeeExpensess extends javax.swing.JFrame {

    /**
     * Creates new form Expensess
     */
    public EmployeeExpensess() {
        initComponents();
        createConnection();
        showDate();
    }
    public void showDate()
    {
        Date d=new Date();
        SimpleDateFormat s=new SimpleDateFormat("yyyy-MM-dd");
        cdate=s.format(d);
        jc2.setDate(d);
    }
    public void createConnection()
    {
        try
        { 
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/garmentsshop","root","root");
        }catch(Exception e)
        {
            
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        socksadd4 = new javax.swing.JLabel();
        socksadd3 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jc2 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        panel1.setBackground(new java.awt.Color(153, 153, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Employee Expenses");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 302, -1));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Date");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 99, -1));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Amount");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, -1));

        tf2.setBackground(new java.awt.Color(249, 215, 184));
        tf2.setFont(new java.awt.Font("Cambria Math", 0, 15)); // NOI18N
        tf2.setForeground(new java.awt.Color(153, 153, 153));
        tf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf2.setText("Amount");
        tf2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf2FocusLost(evt);
            }
        });
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });
        panel1.add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 166, 30));

        socksadd4.setBackground(new java.awt.Color(255, 255, 255));
        socksadd4.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        socksadd4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        socksadd4.setText("Add");
        socksadd4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        socksadd4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        socksadd4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                socksadd4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        socksadd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socksadd4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                socksadd4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                socksadd4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                socksadd4MouseReleased(evt);
            }
        });
        socksadd4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                socksadd4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                socksadd4KeyReleased(evt);
            }
        });
        panel1.add(socksadd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 90, 30));

        socksadd3.setBackground(new java.awt.Color(255, 255, 255));
        socksadd3.setFont(new java.awt.Font("Cambria Math", 1, 18)); // NOI18N
        socksadd3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        socksadd3.setText("Close");
        socksadd3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        socksadd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        socksadd3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                socksadd3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        socksadd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                socksadd3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                socksadd3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                socksadd3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                socksadd3MouseReleased(evt);
            }
        });
        socksadd3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                socksadd3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                socksadd3KeyReleased(evt);
            }
        });
        panel1.add(socksadd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 90, 30));

        cb1.setBackground(new java.awt.Color(249, 215, 184));
        cb1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select EID" }));
        cb1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(187, 120, 52), new java.awt.Color(0, 0, 0)));
        cb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        panel1.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 166, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("EID");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 99, -1));

        jc2.setBackground(new java.awt.Color(249, 215, 184));
        jc2.setDateFormatString("YYYY-MM-dd");
        panel1.add(jc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 166, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String cdate;
int windowcount=0;
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        int sno=0; 
        if(windowcount==0)
        {
           try
           {
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select EID from EmployeeDetails");
            while(rs.next())
            {
                cb1.addItem(""+rs.getInt("EID"));
            }
            }
            catch(Exception e)
            {
            }
           windowcount++;
        }
        else
        {
            
        }
    }//GEN-LAST:event_formWindowGainedFocus
Connection con;
    private void tf2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusGained
        tf2.setText("");
    }//GEN-LAST:event_tf2FocusGained

    private void tf2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyPressed
        tf2.setForeground(Color.black);
    }//GEN-LAST:event_tf2KeyPressed

    private void tf2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyReleased
        tf2.setForeground(Color.black);
    }//GEN-LAST:event_tf2KeyReleased

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped

    }//GEN-LAST:event_tf2KeyTyped

    private void socksadd4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_socksadd4AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4AncestorAdded

    private void socksadd4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd4MouseClicked
        int amount=Integer.parseInt(tf2.getText());
        eid=Integer.parseInt(cb1.getSelectedItem().toString());
        String userdate=((JTextField)jc2.getDateEditor().getUiComponent()).getText();
        try{
            Statement st=con.createStatement();
            st.executeUpdate("insert into employeeexpenses values("+eid+","+amount+",'"+userdate+"')");
            EmployeeExpenseSuccess e=new EmployeeExpenseSuccess();
            e.setVisible(true);
            this.dispose();
        } catch(Exception e)
        {

        }
    }//GEN-LAST:event_socksadd4MouseClicked

    private void socksadd4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4MouseEntered

    private void socksadd4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4MousePressed

    private void socksadd4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4MouseReleased

    private void socksadd4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socksadd4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4KeyPressed

    private void socksadd4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socksadd4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd4KeyReleased

    private void socksadd3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_socksadd3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3AncestorAdded

    private void socksadd3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd3MouseClicked
this.dispose();
    }//GEN-LAST:event_socksadd3MouseClicked

    private void socksadd3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3MouseEntered

    private void socksadd3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3MousePressed

    private void socksadd3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_socksadd3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3MouseReleased

    private void socksadd3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socksadd3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3KeyPressed

    private void socksadd3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_socksadd3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_socksadd3KeyReleased

    private void tf2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf2FocusLost
        String strreason=tf2.getText();
        if(strreason.equals(""))
        {
            tf2.setText("Reason");
        }
    }//GEN-LAST:event_tf2FocusLost
int sno=0;
int eid=0;
    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        String tempemployeeid="";
        tempemployeeid=cb1.getSelectedItem().toString();
        if(tempemployeeid.equals("Select EID"))
        {
            System.out.println("select id");
        }
        else
        {
            
        }
    }//GEN-LAST:event_cb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeExpensess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeExpensess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeExpensess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeExpensess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeExpensess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JDateChooser jc2;
    private java.awt.Panel panel1;
    private javax.swing.JLabel socksadd3;
    private javax.swing.JLabel socksadd4;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
