/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmr.garments;

import static java.nio.file.Files.size;
import static javafx.beans.binding.Bindings.size;

/**
 *
 * @author HP
 */
public class RetailDatabaseQuantityError extends javax.swing.JFrame {

    /**
     * Creates new form RetailDatabaseQuantityError
     */
    public RetailDatabaseQuantityError(int available) {
        initComponents();
        availableqty=available;
        qty1.setText(""+availableqty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        qty1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        size1 = new javax.swing.JLabel();
        item1 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qty1.setFont(new java.awt.Font("Cambria Math", 0, 30)); // NOI18N
        qty1.setForeground(new java.awt.Color(255, 255, 255));
        qty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, 30));

        l2.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("OK");
        l2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        l2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l2MouseEntered(evt);
            }
        });
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 130, -1));

        l3.setFont(new java.awt.Font("Cambria Math", 0, 30)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("quantities are available");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, 30));

        size1.setFont(new java.awt.Font("Cambria Math", 0, 30)); // NOI18N
        size1.setForeground(new java.awt.Color(255, 255, 255));
        size1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(size1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 60, 30));

        item1.setFont(new java.awt.Font("Cambria Math", 0, 30)); // NOI18N
        item1.setForeground(new java.awt.Color(255, 255, 255));
        item1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 560, 30));

        l6.setFont(new java.awt.Font("Cambria Math", 0, 30)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setText("Only ");
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\RMR Garments\\Ritik\\Wrong1.gif")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null, null));
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 317));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int xx,yy;
int availableqty;
String code,size,item;
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xx,y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
        this.dispose();
    }//GEN-LAST:event_l2MouseClicked

    private void l2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseEntered

    }//GEN-LAST:event_l2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetailDatabaseQuantityError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetailDatabaseQuantityError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetailDatabaseQuantityError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetailDatabaseQuantityError.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int available = 0;
                new RetailDatabaseQuantityError(available).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel item1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel qty1;
    private javax.swing.JLabel size1;
    // End of variables declaration//GEN-END:variables
}
